### ISSUE TITLE
How to resolve green from CRIS data?

### ISSUE THREAD

**Issue by bvreede** [bvreede/OAmonitoring#6]
It is hard to predict what elements are present in a CRIS that can be used to resolve green OA.

In 2018, Utrecht University used a combination of columns indicating what kind of document was submitted in their CRIS (Author Accepted Manuscript or Published Version), and the presence of an embargo period. This is hard to replicate and generalize. For one, the notation in another CRIS may be different. Secondly, the presence alone of an embargo period is not a good indicator for something being openly available (though if embargo dates are present, they could be read as dates and confirmed to exist in the current year?).

Unpaywall tends to overestimate green, but  has a more sophisticated ability to look into this (I believe they screen the pdfs themselves for copyright information?). Unpaywall also provides a link to documents, so they also confirm that the document is hosted on a repository.

Unpaywall is the best generalizable option we have at the moment to confirm green... Any other ideas?

**Comment by bvreede** [comment]
The code used last year (just for reference):

```
## Step 3: PURE classification
pure_uu <- mutate(pure_uu,
                  pure_green = str_detect(electronic_version,"Accepted author manuscript")|
                    !is.na(embargo_date))
pure_umcu <- mutate(pure_umcu,
                    pure_green = str_detect(electronic_version,"Accepted author manuscript")|
                      !is.na(embargo_date))
```

**Comment by boer0107** [comment]
Agree that choice for embargo information in UU CRIS might be a very local decision. In theory, these publications should also be indexed by Unpaywall. Perhaps we should test which publications turn up as Green using the Embargo method. Why aren't these in the Unpaywall data (no DOI?). 
Also, your remarks also apply to the pure_hybrid detection (all papers OA in our repository without embargo in publisher version)

**Comment by boer0107** [comment]
We could also decide to make this part of the manual check, not part of the pipe-line itself (although importing the results of a manual check should ideally be part of the pipe-line)

**Comment by boer0107** [comment]
And we should also check how "Taverne" publications end up in our report.

**Comment by kmhettne** [comment]
At Leiden, if a publication has a handle and no embargo, it should be green open access, but I would have to check if this is really the case. I am in favour of allowing for a manual check here.

**Comment by bvreede** [comment]
Letting users do this themselves with custom lists.
