### ISSUE TITLE
Additional labeling options

### ISSUE THREAD

**Issue by bvreede** [bvreede/OAmonitoring#7]
Many universities used Taverne to make output available via the university repository last year. It would be interesting to be able to score these papers separately. Additionally, other universities may have other projects that they want to label independently.

We could envision having the option of either providing a list of DOIs (or system IDs) for papers that a university wants to classify separately, as well as the classification (GOLD/HYBRID/GREEN -- or even an additional option?) and the source.

**Comment by kmhettne** [comment]
At Leiden we have a specific license code for Taverne papers that could be used. Maybe other Universities have implemented such options as well?

**Comment by bvreede** [comment]
I added functionality that mines a custom excel sheet with system_IDs and labels them with custom labels. Taverne can easily be added this way. Closed with PR #12
